### PR TITLE
Fix aomp/test/smoke-fort/flang-471469

### PR DESCRIPTION
**Pull request by TIFitis**

### CODE REVIEW

**Comment by dpalermo** [comment]
No longer asserts, but there is now a memory access fault at runtime (could be a separate issue):

```
[r5 ~/git/aomp20.0/aomp/test/smoke-fort/flang-471469]$ AOMP=/work1/omp-nightly/build/rocm/trunk-atd_20.0-0 make run
Makefile:32: warning: overriding recipe for target 'test'
../Makefile.rules:59: warning: ignoring old recipe for target 'test'
mkdir -p obj
/work1/omp-nightly/build/rocm/trunk-atd_20.0-0/bin/clang -x hip -O3 --offload-arch=gfx90a -c kernel.cpp -o obj/kernel.o
/work1/omp-nightly/build/rocm/trunk-atd_20.0-0/bin/flang-new -O2 -fopenmp -fopenmp-version=50 --offload-arch=gfx90a -c driver.f90 -o obj/driver.o
/work1/omp-nightly/build/rocm/trunk-atd_20.0-0/bin/flang-new -O2 -fopenmp -fopenmp-version=50 --offload-arch=gfx90a -O3 -L/opt/rocm/lib -lamdhip64 -lstdc++ -o test obj/driver.o obj/kernel.o
rm -rf obj
./test  2>&1 | tee run.log
Calling HIP vector_add
No kernel launches known
OFFLOAD ERROR: Memory access fault by GPU 4 (agent 0xfb8d40) at virtual address 0xfca000. Reasons: Unknown (0)
Use 'OFFLOAD_TRACK_ALLOCATION_TRACES=true' to track device allocations
/bin/bash: line 1: 2134469 Aborted                 (core dumped) ./test 2>&1
     2134470 Done                    | tee run.log
make: *** [../Makefile.rules:78: run] Error 134
```

**Review by skatrak — APPROVED** [review]
Thank you Akash! I think we can merge this, since it gets us a bit closer to getting the issues sorted.

**Review by agozillon — APPROVED** [review]
LGTM!

**Comment by dpalermo** [comment]
Latest commit has resolved the runtime error:

```
[r5 ~/git/aomp20.0/aomp/test/smoke-fort/flang-471469]$ AOMP=/work1/omp-nightly/build/rocm/trunk-atd make
 run
Makefile:32: warning: overriding recipe for target 'test'
../Makefile.rules:59: warning: ignoring old recipe for target 'test'
mkdir -p obj
/work1/omp-nightly/build/rocm/trunk-atd/bin/clang -x hip -O3 --offload-arch=gfx90a -c kernel.cpp -o obj/kernel.o
/work1/omp-nightly/build/rocm/trunk-atd/bin/flang-new -O2 -fopenmp -fopenmp-version=50 --offload-arch=gfx90a -c driver.f90 -o obj/driver.o
/work1/omp-nightly/build/rocm/trunk-atd/bin/flang-new -O2 -fopenmp -fopenmp-version=50 --offload-arch=gfx90a -O3 -L/opt/rocm/lib -lamdhip64 -lstdc++ -o test obj/driver.o obj/kernel.o
rm -rf obj
./test  2>&1 | tee run.log
Calling HIP vector_add
Finished HIP vector_add
 c(1) =  3.
echo > /dev/null 2>&1 | tee -a run.log
```

**Pull request merged**
