### PR TITLE
[flang][OpenMP] Fix FlangRuntime offload build after assign change

### PR DESCRIPTION
**Pull request by dpalermo**
- Use actual function for memmove (address taken)

### CODE REVIEW

**Comment by dpalermo** [comment]
Fixed needed after change in https://github.com/llvm/llvm-project/pull/114301

**Comment by dpalermo** [comment]
Also interesting, but the pre-existing libc replacement memmove was missing a return value on the early exit case.  Now fixed.  Reported as a compilation error after no longer using the memmove builtin.

**Comment by dpalermo** [comment]
Raghu noticed the GenASiS target test was no longer finding -lFortranRuntimeHostDevice ...as the build of  libFortranRuntimeHostDevice.a was failing.

**Review by raghavendhra — APPROVED** [review]
Thanks for fixing this :)

**Pull request merged**
