### PR TITLE
Upstreaming warnings suppression from rocMLIR to LLVM project

### PR DESCRIPTION
**Pull request by ivarusic-amd**
Upstreaming this part of code for warning suppression from rocMLIR to LLVM project.

### CODE REVIEW

**Review by krzysz00 — CHANGES_REQUESTED** [review]
1. You're on the wrong repository. Please send this to https://github.com/llvm/llvm-project/ instead
2. This goes into `llvm/cmake/modules/HandleLLVMOptions.cmake`, it looks like, which does all the rest of the MSVC flag mangling.

**Comment by apwojcik** [comment]
@krzysz00, that means we cannot remove a similar change from rocMLIR until you rebase to the llvm-project having the change from this PR merged. Am I correct?

**Comment by krzysz00** [comment]
@apwojcik Yep, that's what that means, and that's fine by us

**Comment by V6ser** [comment]
> @apwojcik Yep, that's what that means, and that's fine by us

I'm glad you're fine, even if that comment sounds super icky. Inefficient decisions/solutions all-around.

**Pull request closed without merging**
