### PR TITLE
Fix failing LLVM and MLIR LIT tests

### PR DESCRIPTION
**Pull request by skatrak**
PR #21 resulted in these broken tests due to changes in the produced IR. This patch updates the tests to expect the new IR.

### CODE REVIEW

**Review by ronlieb — APPROVED** [review]

**Comment by z1-cciauto** [comment]
PSDB Link: https://compiler-ci.amd.com/job/compiler-psdb-amd-staging/2593

**Comment by z1-cciauto** [comment]
PSDB Link: https://compiler-ci.amd.com/job/compiler-psdb-amd-staging/2594

**Comment by z1-cciauto** [comment]
PSDB Link: https://compiler-ci.amd.com/job/compiler-psdb-amd-staging/2595

**Comment by z1-cciauto** [comment]
PSDB Link: https://compiler-ci.amd.com/job/compiler-psdb-amd-staging/2598

**Pull request merged**
